name: Python Package CI/CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Enter the version to update (e.g., 1.0.0)"
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  publish-manually:
    name: Publish to GitHub Release and PyPI (Manually)
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Build a binary wheel and a source tarball
        run: uv build
      - name: Verify distribution files
        run: ls -R dist/
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/
      - name: Create Git tag
        run: |
          git tag "v${{ github.event.inputs.version }}"
          git push origin "v${{ github.event.inputs.version }}"
      - name: Wait for tag to be pushed
        run: |
          # Wait a few seconds to ensure tag is available before proceeding
          sleep 5
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: dist/
      - name: Publish to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          tag_name: v${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
